alias sst="$HOME/server.sh"
alias mst="$HOME/mserver.sh"
alias cs="$HOME/client.sh"
alias ct="git commit -m "
alias act="git commit -am "
alias stt="git status"
alias sd="cd $HOME/projects/analytics-server/"
alias md="cd $HOME/projects/master/analytics-server/"
alias worker="$HOME/worker.sh"
alias batch="$HOME/batch.sh"
alias mister="$HOME/master.sh"
alias x="exit"
alias listb="git branch"
alias pus="git push origin master"
alias pul="git pull origin master"
alias tst="cd $HOME/test"
alias cot="git checkout "
# grep
alias gpyf="grep -rn --include \*.py"
alias gpyfi="grep -rin --include \*.py"
alias gjsf="grep -rn --include \*.js"
alias gjsfi="grep -rin --include \*.js"
alias ghtf="grep -rn --include \*.html"
alias ghtfi="grep -rin --include \*.html"
alias gaf="grep -ril"

