alias sst="$HOME/server.sh"
alias mst="$HOME/mserver.sh"
alias cs="$HOME/client.sh"
alias ct="git commit -m "
alias stt="git status"
alias sd="cd $HOME/projects/analytics-server/"
alias worker="$HOME/worker.sh"
alias batch="$HOME/batch.sh"
alias mister="$HOME/master.sh"
alias x="exit"
alias pus="git push origin master"
alias pul="git pull origin master"
alias tst="cd $HOME/test"
alias cot="git checkout "
# grep
alias gpyf="grep -rin --include \*.py"
alias gaf="grep -rl"

